# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

sudo: required

# apt_packages:
#   - textlive-latex-extra

r_packages:
  - nlme
  - lme4
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

# branches:
#   only:
#     - master
