# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
#  - ./travis-tool.sh aptget_install texlive-latex-extra
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r nlme
  - ./travis-tool.sh install_r lme4
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
  - R_BUILD_ARGS=" " 
  - R_CHECK_ARGS="--as-cran"
  - BOOTSTRAP_LATEX="1"

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - stderr-travis